### ISSUE TITLE
dfaasagent crashes when started without configuration

### ISSUE THREAD

**Issue by ema-pe** [unimib-datAI/dfaas#12]
When I build dfaasagent from `stecattaneo-dev` branch and run it without any arguments or configuration, it just crashes:

```
emanuele@dfaas-next:~/dfaas/dfaasagent$ go1.14.15 build
emanuele@dfaas-next:~/dfaas/dfaasagent$ ./dfaasagent 
INFO	agent/agent.go:124	Libp2p host started. You can connect to this host by using the following multiaddresses:
INFO	agent/agent.go:126	  1. /ip4/127.0.0.1/tcp/37931/p2p/QmbQjrtNjwh9BAnRy2pBSWb8NzdPy6CEToet3tVdcahm6x
INFO	agent/agent.go:126	  2. /ip4/10.0.2.48/tcp/37931/p2p/QmbQjrtNjwh9BAnRy2pBSWb8NzdPy6CEToet3tVdcahm6x
INFO	agent/agent.go:126	  3. /ip4/172.17.0.1/tcp/37931/p2p/QmbQjrtNjwh9BAnRy2pBSWb8NzdPy6CEToet3tVdcahm6x
INFO	agent/agent.go:126	  4. /ip6/::1/tcp/33707/p2p/QmbQjrtNjwh9BAnRy2pBSWb8NzdPy6CEToet3tVdcahm6x
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc413e0]

goroutine 1 [running]:
gitlab.com/team-dfaas/dfaas/node-stack/dfaasagent/agent/loadbalancer.GetStrategyInstance(0x0, 0x0, 0x0, 0x0)
	/home/emanuele/dfaas/dfaasagent/agent/loadbalancer/loadbalancer.go:67 +0xc0
gitlab.com/team-dfaas/dfaas/node-stack/dfaasagent/agent.runAgent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/emanuele/dfaas/dfaasagent/agent/agent.go:136 +0x553
gitlab.com/team-dfaas/dfaas/node-stack/dfaasagent/agent.Main()
	/home/emanuele/dfaas/dfaasagent/agent/agent.go:246 +0x309
main.main()
	/home/emanuele/dfaas/dfaasagent/main.go:8 +0x20
```

This happens because `_strategyFactor` is not properly initialized when the agent is started without a configuration.

**Comment by ema-pe** [comment]
When running dfaasagent with the debugger, it shows that `_config.Strategy` is empty in `Initialize()`. This is wrong: there should always be a default strategy.

```
(dlv) b /home/emanuele/dfaas/dfaasagent/agent/loadbalancer/loadbalancer.go:29
Breakpoint 1 set at 0xffbe42 for gitlab.com/team-dfaas/dfaas/node-stack/dfaasagent/agent/loadbalancer.Initialize() ./agent/loadbalancer/loadbalancer.go:29
(dlv) restart
Process restarted with PID 20307
(dlv) c
INFO	agent/agent.go:124	Libp2p host started. You can connect to this host by using the following multiaddresses:
INFO	agent/agent.go:126	  1. /ip4/127.0.0.1/tcp/37765/p2p/QmNVneMeoKEnYtQmiZqGLdbvXd7F9TMFSjqXTvTGsWx3ea
INFO	agent/agent.go:126	  2. /ip4/10.0.2.48/tcp/37765/p2p/QmNVneMeoKEnYtQmiZqGLdbvXd7F9TMFSjqXTvTGsWx3ea
INFO	agent/agent.go:126	  3. /ip4/172.17.0.1/tcp/37765/p2p/QmNVneMeoKEnYtQmiZqGLdbvXd7F9TMFSjqXTvTGsWx3ea
INFO	agent/agent.go:126	  4. /ip6/::1/tcp/41657/p2p/QmNVneMeoKEnYtQmiZqGLdbvXd7F9TMFSjqXTvTGsWx3ea
> [Breakpoint 1] gitlab.com/team-dfaas/dfaas/node-stack/dfaasagent/agent/loadbalancer.Initialize() ./agent/loadbalancer/loadbalancer.go:29 (hits goroutine(1):1 total:1) (PC: 0xffbe42)
    24:	// Singleton instance representing the strategy adopted from the DFaaS agent
    25:	var _strategyInstance Strategy
    26:	
    27:	// Initialize initializes this package
    28:	func Initialize(p2pHost host.Host, config config.Configuration) {
=>  29:		_p2pHost = p2pHost
    30:		_config = config
    31:		_lock = &sync.Mutex{}
    32:	
    33:		switch _config.Strategy {
    34:		case constants.RecalcStrategy:
(dlv) print config
gitlab.com/team-dfaas/dfaas/node-stack/dfaasagent/agent/config.Configuration {
	DebugMode: false,
	DateTime: false,
	LogColors: false,
	Listen: []string len: 0, cap: 0, nil,
	PrivateKeyFile: "",
	BootstrapNodes: false,
	PublicBootstrapNodes: false,
	BootstrapNodesList: []string len: 0, cap: 0, nil,
	BootstrapNodesFile: "",
	BootstrapForce: false,
	Rendezvous: "",
	MDNSInterval: 0,
	KadIdleTime: 0,
	PubSubTopic: "",
	RecalcPeriod: 0,
	HAProxyTemplateFileNMS: "",
	HAProxyTemplateFileRecalc: "",
	HAProxyConfigFile: "",
	HAProxyConfigUpdateCommand: "",
	HAProxyHost: "",
	HAProxyPort: 0,
	HAProxySockPath: "",
	OpenFaaSHost: "",
	OpenFaaSPort: 0,
	OpenFaaSUser: "",
	OpenFaaSPass: "",
	PrometheusHost: "",
	PrometheusPort: 0,
	HttpServerHost: "",
	HttpServerPort: 0,
	ForecasterHost: "",
	ForecasterPort: 0,
	Strategy: "",
	GroupListFileName: "",
	NodeType: 0,
	CPUThresholdNMS: 0,
	RAMThresholdNMS: 0,
	PowerThresholdNMS: 0,}
(dlv)
```
